const _ = require('underscore');


// map GTFS code to human route
// map human route to GTFS code
// get route service name
// get all route details
function _Routes() {


}

//
// fetch a route object by searching for
// a GTFS route ID
//
_Routes.prototype.fetchBy_gtfs_id = (route_id) => {
    const route = _.find(gtfs_routes, (route) => {
        return route.route_id == route_id;
    });
    return route;
}

// 
// fetch a route object by searching for 
// a human readable route ID
//
_Routes.prototype.fetchBy_human_id = (route_id) => {
    var route_id_string = '';
    // the route ID are strings with a minimum of two characters
    if( route_id < 10 ) {
      route_id_string += '0' + route_id;
    } else {
        route_id_string += route_id;
    }
    const route = _.find(gtfs_routes, (route) => {
        return route.route_short_name == route_id_string;
    });
    return route;
}

// 
// utility to parse a route service name to 
// extract the destination
//
_Routes.prototype.getDestination = (service_name) => {
    const service = service_name.split(':');
    if( service.length > 0 ) {
        return service[1];
    } else {
        return 'unknown';
    }
}

// instantiate the singleton
var routes = new _Routes();
module.exports = routes;

const gtfs_routes = [
  {
   "route_id": "9898",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "01",
   "route_long_name": "",
   "route_service_name": "OLD UNIV:CAP SQR",
   "route_desc": "Weekday schedule trips suspended until further notice.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-1",
   "route_color": "E3D23E",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9899",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "02",
   "route_long_name": "",
   "route_service_name": "WEST TP:NORTH TP",
   "route_desc": "Daily schedule trips operate regularly every 30 minutes.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-2",
   "route_color": "B1006A",
   "route_text_color": "FFFFFF",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9900",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "03",
   "route_long_name": "",
   "route_service_name": "WEST TP:EAST TP",
   "route_desc": "Weekday schedule trips suspended until further notice.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-3",
   "route_color": "CD8382",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9901",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "04",
   "route_long_name": "",
   "route_service_name": "SOUTH TP:NORTH TP",
   "route_desc": "Daily schedule trips operate regularly every 60 minutes. Additional weekday schedule trips operate regularly at least every 30 minutes from approximately 6 AM until 6 PM.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-4",
   "route_color": "007A49",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9902",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "05",
   "route_long_name": "",
   "route_service_name": "SOUTH TP:EAST TP",
   "route_desc": "Daily schedule trips operate regularly every 60 minutes. Additional weekday schedule trips operate regularly at least every 30 minutes from approximately 6 AM until 6 PM.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-5",
   "route_color": "B76A5C",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9903",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "06",
   "route_long_name": "",
   "route_service_name": "E TOWNE:WEST TP",
   "route_desc": "Daily schedule trips operate regularly every 30 minutes. Limited trips operate via Tokay and Madison College.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-6",
   "route_color": "ED1C25",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9904",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "07",
   "route_long_name": "",
   "route_service_name": "WEST TP:EAST TP",
   "route_desc": "Daily schedule trips operate regularly every 30 minutes. Limited trips via Tokay and Regent suspended until further notice.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-7",
   "route_color": "A8C32E",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9905",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "08",
   "route_long_name": "",
   "route_service_name": "SPRNG HB:CAP SQR",
   "route_desc": "Daily schedule trips operate regularly every 60 minutes. Additional weekday schedule trips operate regularly at least every 30 minutes from approximately 6 AM until 6 PM.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-8",
   "route_color": "B2DF8A",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9906",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "10",
   "route_long_name": "",
   "route_service_name": "UNIV ROW:UNION CS",
   "route_desc": "Weekday schedule trips suspended until further notice.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-10",
   "route_color": "F88179",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9907",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "11",
   "route_long_name": "",
   "route_service_name": "DUTCH ML:WEST TP",
   "route_desc": "Weekday schedule trips operate regularly eastbound every 60 minutes from approximately 6 AM until 9 AM and westbound every 60 minutes from approximately 3 PM until 6 PM.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-11",
   "route_color": "749883",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9908",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "12",
   "route_long_name": "",
   "route_service_name": "DUTCH ML:WEST TP",
   "route_desc": "Weekday schedule trips operate regularly westbound every 60 minutes from approximately 6 AM until 9 AM and eastbound every 60 minutes from approximately 3 PM until 6 PM.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-12",
   "route_color": "C1A322",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9909",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "13",
   "route_long_name": "",
   "route_service_name": "U CAMPUS:SOUTH TP",
   "route_desc": "Daily schedule trips operate regularly every 60 minutes.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-13",
   "route_color": "793817",
   "route_text_color": "FFFFFF",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9910",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "14",
   "route_long_name": "",
   "route_service_name": "WEXFD RG:ETP/SQR",
   "route_desc": "Weekday schedule trips suspended until further notice.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-14",
   "route_color": "778D22",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9911",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "15",
   "route_long_name": "",
   "route_service_name": "HIGH PT:EAST TP",
   "route_desc": "Weekday schedule trips operate regularly every 60 minutes. Additional schedule trips operate regularly at least every 30 minutes from approximately 6 AM until 6 PM. Trips via Junction and Greenway suspended until further notice.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-15",
   "route_color": "FFCC00",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9912",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "16",
   "route_long_name": "",
   "route_service_name": "SOUTH TP:EAST TP",
   "route_desc": "Daily schedule trips operate regularly every 60 minutes. Additional weekday schedule trips operate regularly at least every 30 minutes from approximately 6 AM until 6 PM.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-16",
   "route_color": "B973B1",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9913",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "17",
   "route_long_name": "",
   "route_service_name": "NORTH TP:EAST TP",
   "route_desc": "Daily schedule trips operate regularly every 30 minutes.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-17",
   "route_color": "356DB7",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9914",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "18",
   "route_long_name": "",
   "route_service_name": "WEST TP:SOUTH TP",
   "route_desc": "Daily schedule trips operate regularly every 30 minutes. Limited trips operate via Hammersley and Coho.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-18",
   "route_color": "3169B4",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9915",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "19",
   "route_long_name": "",
   "route_service_name": "DUNNS MARSH:CAP SQR",
   "route_desc": "Weekday schedule trips suspended until further notice.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-19",
   "route_color": "B8DB99",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9916",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "20",
   "route_long_name": "",
   "route_service_name": "E TOWNE:NORTH TP",
   "route_desc": "Daily schedule trips operate regularly every 30 minutes. Limited trips via Shopko suspended until further notice.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-20",
   "route_color": "D7B884",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9917",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "21",
   "route_long_name": "",
   "route_service_name": "LAKEVIEW:NORTH TP",
   "route_desc": "Daily schedule trips operate regularly every 60 minutes. Additional weekday schedule trips operate regularly at least every 30 minutes from approximately 6 AM until 6 PM.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-21",
   "route_color": "42379E",
   "route_text_color": "FFFFFF",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9918",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "22",
   "route_long_name": "",
   "route_service_name": "MENDOTA:NORTH TP",
   "route_desc": "Daily schedule trips operate regularly every 60 minutes. Additional weekday schedule trips operate regularly at least every 30 minutes from approximately 6 AM until 6 PM.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-22",
   "route_color": "51BF9D",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9919",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "23",
   "route_long_name": "",
   "route_service_name": "S PRAIRIE:CAP SQR",
   "route_desc": "Weekday schedule trips operate regularly every 30 minutes from approximately 6 AM until 8 AM and 4 PM until 6 PM.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-23",
   "route_color": "F8951D",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9920",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "25",
   "route_long_name": "",
   "route_service_name": "AMERICAN:CAP SQR",
   "route_desc": "Weekday schedule trips suspended until further notice.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-25",
   "route_color": "A29F9A",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9921",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "26",
   "route_long_name": "",
   "route_service_name": "AMERICAN:E TOWNE",
   "route_desc": "Daily schedule trips operate regularly every 30 minutes.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-26",
   "route_color": "6F3A97",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9922",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "27",
   "route_long_name": "",
   "route_service_name": "U CAMPUS:NORTH TP",
   "route_desc": "Weekday schedule trips suspended until further notice.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-27",
   "route_color": "7EC3D3",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9923",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "28",
   "route_long_name": "",
   "route_service_name": "NORTH TP:WEST TP",
   "route_desc": "Weekday schedule trips operate regularly every 30 minutes from approximately 6 AM until 6 PM.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-28",
   "route_color": "6AB6D1",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9924",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "29",
   "route_long_name": "",
   "route_service_name": "SCHOOL:BREESE",
   "route_desc": "Weekday schedule trips suspended until further notice.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-29",
   "route_color": "5C99A5",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9925",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "30",
   "route_long_name": "",
   "route_service_name": "E TOWNE:EAST TP",
   "route_desc": "Daily schedule trips operate regularly every 30 minutes.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-30",
   "route_color": "B15928",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9926",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "31",
   "route_long_name": "",
   "route_service_name": "MARSH RD:EAST TP",
   "route_desc": "Daily schedule trips operate regularly every 60 minutes. All trips operate via Dutch Mill.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-31",
   "route_color": "9A061B",
   "route_text_color": "FFFFFF",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9927",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "32",
   "route_long_name": "",
   "route_service_name": "ACEWOOD-THOMPSON:ETP",
   "route_desc": "Daily schedule trips operate regularly every 60 minutes.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-32",
   "route_color": "F173AC",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9928",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "33",
   "route_long_name": "",
   "route_service_name": "SPRECHER:ETP",
   "route_desc": "Weekday schedule trips operate regularly every 30 minutes from approximately 6 AM until 9 AM and 3 PM until 6 PM. Route modified and stops east of Sprecher suspended until further notice.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-33",
   "route_color": "33A02C",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9929",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "34",
   "route_long_name": "",
   "route_service_name": "MATC:EAST TP",
   "route_desc": "Weekday schedule trips suspended until further notice.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-34",
   "route_color": "976C25",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9930",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "35",
   "route_long_name": "",
   "route_service_name": "ATLAS-ACEWOOD:ETP",
   "route_desc": "Weekday schedule trips suspended until further notice.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-35",
   "route_color": "C8537D",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9931",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "36",
   "route_long_name": "",
   "route_service_name": "E SPRINGS:E TOWNE",
   "route_desc": "Daily schedule trips operate regularly every 60 minutes.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-36",
   "route_color": "00A99D",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9932",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "37",
   "route_long_name": "",
   "route_service_name": "SHEBOYGN:PFLAUM",
   "route_desc": "Weekday schedule trips suspended until further notice.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-37",
   "route_color": "CB6B77",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9933",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "38",
   "route_long_name": "",
   "route_service_name": "UNIV ROW:PFLAUM",
   "route_desc": "Weekday schedule trips operate regularly every 30 minutes from approximately 6 AM until 6 PM. Trips between approximately 9 AM and 3 PM operate University Row to/from Ingersoll Street only.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-38",
   "route_color": "8D89B3",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9934",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "39",
   "route_long_name": "",
   "route_service_name": "WORLD DY:EAST TP",
   "route_desc": "Weekday schedule trips operate regularly every 60 minutes from approximately 6 AM until 6 PM. All trips operate via Dempsey.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-39",
   "route_color": "52BEE6",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9935",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "40",
   "route_long_name": "",
   "route_service_name": "GRNDVIEW/TODD:STP",
   "route_desc": "Daily schedule trips operate regularly every 60 minutes. Additional weekday schedule trips operate regularly at least every 30 minutes from approximately 6 AM until 6 PM. Limited weekday trips operate via Todd.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-40",
   "route_color": "00AFD1",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9936",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "44",
   "route_long_name": "",
   "route_service_name": "U CAMPUS:SOUTH TP",
   "route_desc": "Weekday schedule trips operate regularly northbound every 30 minutes from approximately 6 AM until 9 AM and southbound every 30 minutes from approximately 3 PM until 6 PM.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-44",
   "route_color": "A794B4",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9937",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "47",
   "route_long_name": "",
   "route_service_name": "ARBOR HL:CAP SQR",
   "route_desc": "Weekday schedule trips suspended until further notice.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-47",
   "route_color": "885CA0",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9938",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "48",
   "route_long_name": "",
   "route_service_name": "U CAMPUS:SOUTH TP",
   "route_desc": "Weekday schedule trips operate regularly every 30 minutes southbound from approximately 7 AM until 8 AM and northbound every 30 minutes from approximately 4 PM until 5 PM.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-48",
   "route_color": "F173AC",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9939",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "49",
   "route_long_name": "",
   "route_service_name": "LACY-HATCHERY:SOUTH TP",
   "route_desc": "Weekday schedule trips operate regularly every 30 minutes from approximately 6 AM until 8 AM and 4 PM until 6 PM.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-49",
   "route_color": "81C342",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9940",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "50",
   "route_long_name": "",
   "route_service_name": "RAYMOND:WEST TP",
   "route_desc": "Weekday schedule trips operate regularly every 30 minutes. Weekend/holiday trips operate regularly every 60 minutes.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-50",
   "route_color": "33A02C",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9941",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "51",
   "route_long_name": "",
   "route_service_name": "MUIR FLD:WEST TP",
   "route_desc": "Daily schedule trips operate regularly every 60 minutes.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-51",
   "route_color": "EE4E9C",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9942",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "52",
   "route_long_name": "",
   "route_service_name": "ORCHARD PT:WEST TP",
   "route_desc": "Weekday schedule trips operate regularly every 60 minutes.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-52",
   "route_color": "7E2654",
   "route_text_color": "FFFFFF",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9943",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "55",
   "route_long_name": "",
   "route_service_name": "VERONA:WEST TP",
   "route_desc": "Weekday schedule trips operate at least every 60 minutes from approximately 7 AM until 9 AM and 5 PM until 7 PM.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-55",
   "route_color": "5187A9",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9944",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "56",
   "route_long_name": "",
   "route_service_name": "MC KEE:NORTH TP/WTP",
   "route_desc": "Weekday schedule trips suspended until further notice.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-56",
   "route_color": "937A6C",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9945",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "57",
   "route_long_name": "",
   "route_service_name": "MC KEE:NORTH TP/WTP",
   "route_desc": "Weekday schedule trips suspended until further notice.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-57",
   "route_color": "84743E",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9946",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "58",
   "route_long_name": "",
   "route_service_name": "GRNTREE:CAP SQR",
   "route_desc": "Weekday schedule trips suspended until further notice.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-58",
   "route_color": "A0A197",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9947",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "59",
   "route_long_name": "",
   "route_service_name": "FITCHBURG:WEST TP",
   "route_desc": "Weekend/holiday trips operate regularly every 60 minutes.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-59",
   "route_color": "FFCC00",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9948",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "63",
   "route_long_name": "",
   "route_service_name": "PR TOWN:WEST TP",
   "route_desc": "Weekend/holiday trips operate regularly every 60 minutes.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-63",
   "route_color": "EB9E18",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9949",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "67",
   "route_long_name": "",
   "route_service_name": "W TOWNE:WEST TP",
   "route_desc": "Daily schedule trips operate regularly every 30 minutes.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-67",
   "route_color": "9B76B8",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9950",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "68",
   "route_long_name": "",
   "route_service_name": "PR TOWN:WEST TP",
   "route_desc": "Weekend/holiday trips operate regularly every 60 minutes.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-68",
   "route_color": "52BEE6",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9951",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "70",
   "route_long_name": "",
   "route_service_name": "MIDDLTON:CAP SQR",
   "route_desc": "Weekday schedule trips operate regularly every 60 minutes.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-70",
   "route_color": "A7B5DC",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9952",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "71",
   "route_long_name": "",
   "route_service_name": "MIDDLTON:CAP SQR",
   "route_desc": "Weekday schedule trips suspended until further notice.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-71",
   "route_color": "B67F72",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9953",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "72",
   "route_long_name": "",
   "route_service_name": "MIDDLTON:CAP SQR",
   "route_desc": "Weekday schedule trips operate regularly every 30 minutes eastbound from approximately 6 AM until 8 AM and westbound every 30 minutes from approximately 3 PM until 5 PM. Limited trips operate westbound in the AM and eastbound in the PM.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-72",
   "route_color": "9A061B",
   "route_text_color": "FFFFFF",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9954",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "73",
   "route_long_name": "",
   "route_service_name": "MIDDLTON:WEST TP",
   "route_desc": "Weekday schedule trips operate regularly every 60 minutes.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-73",
   "route_color": "FF7F00",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9955",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "75",
   "route_long_name": "",
   "route_service_name": "VERONA:CAP SQR",
   "route_desc": "Weekday schedule trips operate at least every 60 minutes from approximately 7 AM until 9 AM and 5 PM until 7 PM.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-75",
   "route_color": "FAA61A",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9956",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "78",
   "route_long_name": "",
   "route_service_name": "MIDDLTON:WEST TP",
   "route_desc": "Weekend schedule trips operate regularly every 60 minutes.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-78",
   "route_color": "749883",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9957",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "80",
   "route_long_name": "",
   "route_service_name": "UW CAMPUS:UNION",
   "route_desc": "Daily schedule trips operate at least every 50 minutes. Additional weekday schedule trips operate at least every 15 minutes from approximately 7 AM until 6 PM. Trips operate on limited Campus Holidays only.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-80",
   "route_color": "CE2A1E",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9958",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "81",
   "route_long_name": "",
   "route_service_name": "JOHNSON/W WASH:UNION",
   "route_desc": "Daily schedule trips operate regularly every 30 minutes from approximately 6 PM until 2 AM. No trips operate during Campus Recess or on Campus Holidays.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-81",
   "route_color": "F68B1F",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9959",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "82",
   "route_long_name": "",
   "route_service_name": "OBSRVTRY/BREESE:UNION",
   "route_desc": "Daily schedule trips operate regularly every 30 minutes from approximately 6 PM until 2 AM. No trips operate during Campus Recess or on Campus Holidays.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-82",
   "route_color": "006CB7",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  },
  {
   "route_id": "9960",
   "service_id": "99",
   "agency_id": "MMT",
   "route_short_name": "84",
   "route_long_name": "",
   "route_service_name": "EAGLE HTS:UW CAMPUS",
   "route_desc": "Weekday schedule trips operate at least every 30 minutes from approximately 4 PM until 7 PM. Additional weekday schedule trips operate on Standard service days only from approximately 9 AM until 4 PM.",
   "route_type": "3",
   "route_url": "http://www.cityofmadison.com/metro/routes-schedules/route-84",
   "route_color": "6A3393",
   "route_text_color": "000000",
   "bikes_allowed": "1"
  }
 ]