module.exports = [
  {
    "route_id": 8216,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": "01",
    "route_long_name": "",
    "route_service_name": "OLD UNIV:CAP SQR",
    "route_desc": "Serves Capitol Square to/from Old University Avenue. Operates regularly in both directions only from about 9 AM to 3 PM on weekday service days.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route01/",
    "route_color": "E3D23E",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8217,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": "02",
    "route_long_name": "",
    "route_service_name": "WEST TP:NORTH TP",
    "route_desc": "Serves West Transfer Point to/from North Transfer Point. Operates regularly in both directions during entire day on every service day.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route02/",
    "route_color": "981F66",
    "route_text_color": "FFFFFF",
    "bikes_allowed": 1
  },
  {
    "route_id": 8218,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": "03",
    "route_long_name": "",
    "route_service_name": "WEST TP:EAST TP",
    "route_desc": "Serves West Transfer Point to/from East Transfer Point. Operates regularly in both directions during entire day on weekday service days only.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route03/",
    "route_color": "CD8382",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8219,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": "04",
    "route_long_name": "",
    "route_service_name": "SOUTH TP:NORTH TP",
    "route_desc": "Serves South Transfer Point to/from North Transfer Point. Operates regularly in both directions during entire day on every service day.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route04/",
    "route_color": "42784D",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8220,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": "05",
    "route_long_name": "",
    "route_service_name": "SOUTH TP:EAST TP",
    "route_desc": "Serves South Transfer Point to/from East Transfer Point. Operates regularly in both directions during entire day on every service day.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route05/",
    "route_color": "B46A5B",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8221,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": "06",
    "route_long_name": "",
    "route_service_name": "E TOWNE:WEST TP",
    "route_desc": "Serves West Transfer Point to/from East Towne Mall. Operates regularly in both directions during entire day on every service day; via Tokay and MATC only during weekday service days.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route06/",
    "route_color": "CC382C",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8222,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": "07",
    "route_long_name": "",
    "route_service_name": "WEST TP:EAST TP",
    "route_desc": "Serves West Transfer Point to/from East Transfer Point. Operates regularly in both directions during entire day on weekend and holiday/modified service days only.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route07/",
    "route_color": "AEC34B",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8223,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": "08",
    "route_long_name": "",
    "route_service_name": "SPRNG HB:CAP SQR",
    "route_desc": "Serves Capitol Square to/from Spring Harbor. Operates regularly in both directions during entire day on weekend and holiday/modified service days only.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route08/",
    "route_color": "D8A464",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8224,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 10,
    "route_long_name": "",
    "route_service_name": "UNIV ROW:UNION CS",
    "route_desc": "Serves University Row to/from Union Corners. Operates regularly in both directions on weekday service days only; between University Row and UW Campus from about 7 AM to 10 PM; between Union Corners and UW Campus from about 7 AM to 6 PM.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route10/",
    "route_color": 919249,
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8225,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 11,
    "route_long_name": "",
    "route_service_name": "DUTCH ML:WEST TP",
    "route_desc": "Serves West Transfer Point to/from UW Campus-Capitol Square-Dutch Mill. Operates regularly in Dutch Mill direction from about 6 AM to 9 AM and in West Transfer Point direction from about 3 PM to 6 PM on weekday service days only.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route11/",
    "route_color": "D3886A",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8226,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 12,
    "route_long_name": "",
    "route_service_name": "DUTCH ML:WEST TP",
    "route_desc": "Serves Dutch Mill to/from Capitol Square-West Transfer Point. Operates regularly in West Transfer Point direction from about 6 AM to 9 AM and in Dutch Mill direction from about 3 PM to 6 PM on weekday service days only.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route12/",
    "route_color": "9B8821",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8227,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 13,
    "route_long_name": "",
    "route_service_name": "U CAMPUS:SOUTH TP",
    "route_desc": "Serves South Transfer Point to/from UW Campus. Operates regularly in both directions during entire day on every service day.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route13/",
    "route_color": "803E0E",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8228,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 14,
    "route_long_name": "",
    "route_service_name": "WEXFD RG:ETP/SQR",
    "route_desc": "Serves Wexford Ridge to/from Capitol Square-East Transfer Point. Operates regularly in both directions on weekday service days only; between Wexford Ridge and Capitol Square during entire day; between East Transfer Point and Capitol Square only from about 6 AM to 9 AM and 3 PM to 6 PM.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route14/",
    "route_color": "778D22",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8229,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 15,
    "route_long_name": "",
    "route_service_name": "JUNCT RG:ETP/SQR",
    "route_desc": "Serves Junction Ridge to/from Capitol Square-East Transfer Point. Operates regularly in both directions on weekday service days only; between Junction Ridge and Capitol Square during entire day; between East Transfer Point and Capitol Square and via Greenway only from about 6 AM to 9 AM and 3 PM to 7 PM.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route15/",
    "route_color": "C3C946",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8230,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 16,
    "route_long_name": "",
    "route_service_name": "SOUTH TP:EAST TP",
    "route_desc": "Serves South Transfer Point to/from East Transfer Point. Operates regularly in both directions during entire day on every service day.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route16/",
    "route_color": "B86FAD",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8231,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 17,
    "route_long_name": "",
    "route_service_name": "NORTH TP:EAST TP",
    "route_desc": "Serves North Transfer Point to/from East Transfer Point. Operates regularly in both directions from about 6 AM to 10 PM on weekday service days; during entire day on weekend and holiday/modified service days.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route17/",
    "route_color": "4D6BB1",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8232,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 18,
    "route_long_name": "",
    "route_service_name": "WEST TP:SOUTH TP",
    "route_desc": "Serves West Transfer Point to/from South Transfer Point. Operates regularly in both directions during entire day on every service day.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route18/",
    "route_color": "4A67AE",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8233,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 19,
    "route_long_name": "",
    "route_service_name": "DUNNS MARSH:CAP SQR",
    "route_desc": "Serves Dunns Marsh to/from Capitol Square. Operates regularly in both directions on weekday service days only.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route19/",
    "route_color": "B8DB99",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8234,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 20,
    "route_long_name": "",
    "route_service_name": "E TOWNE:NORTH TP",
    "route_desc": "Serves North Transfer Point to/from East Towne Mall. Operates regularly in both directions during entire day on every service day; via Shopko only during evenings on weekday service days and entire day on weekend and holiday/modified service days.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route20/",
    "route_color": "A7533E",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8235,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 21,
    "route_long_name": "",
    "route_service_name": "LAKEVIEW:NORTH TP",
    "route_desc": "Serves North Transfer Point to/from Lakeview. Operates regularly during entire day on every service day.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route21/",
    "route_color": "7F9784",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8236,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 22,
    "route_long_name": "",
    "route_service_name": "MENDOTA:NORTH TP",
    "route_desc": "Serves North Transfer Point to/from Mendota. Operates regularly during entire day on every service day.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route22/",
    "route_color": "7DBC9F",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8237,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 25,
    "route_long_name": "",
    "route_service_name": "AMERICAN:CAP SQR",
    "route_desc": "Serves Capitol Square to/from American Center. Operates limited trips in American Center direction in the morning and afternoon and limited trips in Capitol Square direction in the afternoon on weekday service days only.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route25/",
    "route_color": "A29F9A",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8238,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 26,
    "route_long_name": "",
    "route_service_name": "AMERICAN:E TOWNE",
    "route_desc": "Serves East Towne Mall to/from American Center. Operates regularly from about 6 AM to 10 PM on weekday service days; during entire day on weekend and holiday/modified service days.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route26/",
    "route_color": "653A91",
    "route_text_color": "FFFFFF",
    "bikes_allowed": 1
  },
  {
    "route_id": 8239,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 27,
    "route_long_name": "",
    "route_service_name": "U CAMPUS:NORTH TP",
    "route_desc": "Serves North Transfer Point to/from UW Campus. Operates regularly in UW Campus direction from about 6 AM to 9 AM and in North Transfer Point direction from about 3 PM to 6 PM on weekday service days only; limited trips in opposite direction during morning and afternoon.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route27/",
    "route_color": "7DC0D0",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8240,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 28,
    "route_long_name": "",
    "route_service_name": "NORTH TP:WEST TP",
    "route_desc": "Serves North Transfer Point to/from West Transfer Point. Operates regularly in West Transfer Point direction from about 5 AM to 9 AM and in North Transfer Point direction from about 2 PM to 6 PM on weekday service days only.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route28/",
    "route_color": "6AB6D1",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8241,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 29,
    "route_long_name": "",
    "route_service_name": "SCHOOL:BREESE",
    "route_desc": "Serves School Road to/from UW Campus-Breese Terrace. Operates limited trips in UW Campus direction in the morning and limited trips in School Road direction in the afternoon on weekday service days only.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route29/",
    "route_color": "5C99A5",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8242,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 30,
    "route_long_name": "",
    "route_service_name": "E TOWNE:EAST TP",
    "route_desc": "Serves East Transfer Point to/from East Towne Mall. Operates regularly during entire day on every service day.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route30/",
    "route_color": "DA8A39",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8243,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 31,
    "route_long_name": "",
    "route_service_name": "MARSH RD:EAST TP",
    "route_desc": "Serves East Transfer Point to/from Marsh Road. Operates regularly in both directions from about 7 AM to 10 AM and 4 PM to 11 PM on weekday service days; operates regularly in both directions via Dutch Mill during entire day on weekend and holiday/modified service days.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route31/",
    "route_color": "841D1D",
    "route_text_color": "FFFFFF",
    "bikes_allowed": 1
  },
  {
    "route_id": 8244,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 32,
    "route_long_name": "",
    "route_service_name": "ACEWOOD-THOMPSON:ETP",
    "route_desc": "Serves East Transfer Point to/from Acewood-Thompson. Operates regularly in Acewood direction at about 2 PM and from 7 PM to 11 PM on weekday service days only; operates regularly in Thompson direction from about 9 AM to 1 PM on weekday service days and during entire day on weekend and holiday/modified service days.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route32/",
    "route_color": "5580A9",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8245,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 33,
    "route_long_name": "",
    "route_service_name": "SPRECHER-THOMPSON:ETP",
    "route_desc": "Serves East Transfer Point to/from Sprecher-Thompson. Operates regularly in Sprecher direction from about 6 AM to 9 AM on weekday service days; operates regularly in Thompson direction from about 3 PM to 6 PM on weekday service days.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route33/",
    "route_color": "5FA79D",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8246,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 34,
    "route_long_name": "",
    "route_service_name": "MATC:EAST TP",
    "route_desc": "Serves East Transfer Point to/from MATC Truax. Operates regularly only from about 7 AM to 6 PM on weekday service days.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route34/",
    "route_color": "976C25",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8247,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 35,
    "route_long_name": "",
    "route_service_name": "ATLAS-ACEWOOD:ETP",
    "route_desc": "Serves East Transfer Point to/from Atlas-Acewood. Operates regularly in Atlas direction from about 6 AM to 9 AM on weekday service days; operates regularly in Acewood direction from about 3 PM to 6 PM on weekday service days.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route35/",
    "route_color": "C8537D",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8248,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 36,
    "route_long_name": "",
    "route_service_name": "E SPRINGS:E TOWNE",
    "route_desc": "Serves East Towne Mall to/from East Springs. Operates regularly during entire day on every service day.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route36/",
    "route_color": "4D5613",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8249,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 37,
    "route_long_name": "",
    "route_service_name": "SHEBOYGN:PFLAUM",
    "route_desc": "Serves Sheboygan Avenue to/from Pflaum Road. Operates regularly in Pflaum Road direction from about 7 AM to 10 AM and in Sheboygan Avenue direction from about 4 PM to 6 PM on weekday service days only.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route37/",
    "route_color": "CB6B77",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8250,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 38,
    "route_long_name": "",
    "route_service_name": "SHEBOYGN:PFLAUM",
    "route_desc": "Serves Pflaum Road to/from UW Campus-Sheboygan Avenue. Operates regularly in Sheboygan Avenue direction from about 5 AM to 9 AM and in Pflaum Road direction from about 3 PM to 6 PM on weekday service days only.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route38/",
    "route_color": "8D89B3",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8251,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 39,
    "route_long_name": "",
    "route_service_name": "WORLD DY:EAST TP",
    "route_desc": "Serves East Transfer Point to/from World Dairy. Operates regularly from about 7 AM to 6 PM on weekday service days; limited trips via Dempsey at about 7 AM and 6 PM and from about 10 AM to 3 PM.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route39/",
    "route_color": "7493A8",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8252,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 40,
    "route_long_name": "",
    "route_service_name": "GRNDVIEW/TODD:STP",
    "route_desc": "Serves South Transfer Point to/from Todd/Grandview. Operates regularly in Todd direction only from about 6 AM to 6 PM on weekday service days only; operates regularly in Grandview direction before 6 AM - from 9 AM to 4 PM and 6 PM to 11 PM on weekday service days and during entire day on weekend and holiday/modified service days.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route40/",
    "route_color": "64ACCD",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8253,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 44,
    "route_long_name": "",
    "route_service_name": "U CAMPUS:SOUTH TP",
    "route_desc": "Serves South Transfer Point to/from UW Campus. Operates regularly in UW Campus direction from about 6 AM to 9 AM and in South Transfer Point direction from about 3 PM to 6 PM on weekday service days only.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route44/",
    "route_color": "8F8A64",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8254,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 47,
    "route_long_name": "",
    "route_service_name": "ARBOR HL:CAP SQR",
    "route_desc": "Serves Arbor Hills to/from Capitol Square. Operates regularly in both directions from about 6 AM to 9 AM and 3 PM to 6 PM on weekday service days only.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route47/",
    "route_color": "885CA0",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8255,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 48,
    "route_long_name": "",
    "route_service_name": "U CAMPUS:SOUTH TP",
    "route_desc": "Serves UW Campus to/from South Transfer Point. Operates regularly in South Transfer Point direction from about 6 AM to 8 AM and in UW Campus direction from about 4 PM to 6 PM on weekday service days only.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route48/",
    "route_color": "D77AA9",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8256,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 49,
    "route_long_name": "",
    "route_service_name": "LACY-HATCHERY:SOUTH TP",
    "route_desc": "Serves South Transfer Point to/from Lacy-Hatchery Hill. Operates regularly in Hatchery Hill direction from about 6 AM to 9 AM on weekday service days; operates regularly in Lacy direction from about 4 PM to 6 PM on weekday service days.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route49/",
    "route_color": "7FC241",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8257,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 50,
    "route_long_name": "",
    "route_service_name": "RAYMOND:WEST TP",
    "route_desc": "Serves West Transfer Point to/from Raymond. Operates regularly during entire day on every service day.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route50/",
    "route_color": "D77734",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8258,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 51,
    "route_long_name": "",
    "route_service_name": "MUIR FLD:WEST TP",
    "route_desc": "Serves West Transfer Point to/from Muir Field. Operates regularly from about 9 AM to 3 PM and 5 PM to 11 PM on weekday service days; operates regularly during entire day on weekend and holiday/modified service days.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route51/",
    "route_color": "D05898",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8259,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 52,
    "route_long_name": "",
    "route_service_name": "ORCHARD PT:WEST TP",
    "route_desc": "Serves West Transfer Point to/from Orchard Pointe. Operates regularly in both directions from about 6 AM to 10 PM on weekday service days only.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route52/",
    "route_color": "6D2C50",
    "route_text_color": "FFFFFF",
    "bikes_allowed": 1
  },
  {
    "route_id": 8260,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 55,
    "route_long_name": "",
    "route_service_name": "VERONA:WEST TP",
    "route_desc": "Serves West Transfer Point to/from Mid Town-Epic Campus. Operates limited trips in both directions in the morning and afternoon on weekday and modified service days only.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route55/",
    "route_color": "D5BC5B",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8261,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 56,
    "route_long_name": "",
    "route_service_name": "MC KEE:NORTH TP/WTP",
    "route_desc": "Serves McKee Road to/from West Transfer Point-North Transfer Point. Operates regularly in North Transfer Point direction from about 6 AM to 9 AM and in McKee Road direction from about 3 PM to 6 PM on weekday service days only; operates regularly in both directions between McKee Road and West Transfer Point.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route56/",
    "route_color": "937A6C",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8262,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 57,
    "route_long_name": "",
    "route_service_name": "MC KEE:NORTH TP/WTP",
    "route_desc": "Serves McKee Road to/from West Transfer Point-North Transfer Point. Operates regularly in North Transfer Point direction from about 6 AM to 9 AM and in McKee Road direction from about 3 PM to 6 PM on weekday service days only; operates regularly in both directions between McKee Road and West Transfer Point.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route57/",
    "route_color": "84743E",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8263,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 58,
    "route_long_name": "",
    "route_service_name": "GRNTREE:CAP SQR",
    "route_desc": "Serves Greentree to/from Capitol Square. Operates regularly in Capitol Square direction from about 6 AM to 9 AM and in Greentree direction from about 3 PM to 6 PM on weekday service days only; limited trips in opposite direction during morning and afternoon.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route58/",
    "route_color": "A0A197",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8264,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 59,
    "route_long_name": "",
    "route_service_name": "FITCHBURG:WEST TP",
    "route_desc": "Serves West Transfer Point to/from Orchard Pointe-Fitchburg. Operates regularly in both directions during entire day on weekend and holiday/modified service days only.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route59/",
    "route_color": "E09FC0",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8265,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 63,
    "route_long_name": "",
    "route_service_name": "PR TOWN:WEST TP",
    "route_desc": "Serves West Transfer Point to/from Prairie Towne Center. Operates regularly in both directions during entire day on weekend and holiday/modified service days only.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route63/",
    "route_color": "D7A23A",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8266,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 67,
    "route_long_name": "",
    "route_service_name": "W TOWNE:WEST TP",
    "route_desc": "Serves West Transfer Point to/from West Towne Mall. Operates regularly during entire day on every service day.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route67/",
    "route_color": "6584A4",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8267,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 68,
    "route_long_name": "",
    "route_service_name": "PR TOWN:WEST TP",
    "route_desc": "Serves West Transfer Point to/from Prairie Towne Center. Operates regularly in both directions during entire day on weekend and holiday/modified service days only.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route68/",
    "route_color": "5EA95A",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8268,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 70,
    "route_long_name": "",
    "route_service_name": "MIDDLTON:CAP SQR",
    "route_desc": "Serves Middleton to/from Capitol Square. Operates regularly from about 9 AM to 3 PM and 6 PM to 11 PM on weekday service days; limited trips in Capitol Square direction from about 5 AM to 6 AM.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route70/",
    "route_color": "A8B1DA",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8269,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 71,
    "route_long_name": "",
    "route_service_name": "MIDDLTON:CAP SQR",
    "route_desc": "Serves Middleton to/from Capitol Square. Operates regularly in Capitol Square direction from about 6 AM to 9 AM and in Middleton direction from about 3 PM to 6 PM on weekday service days only; limited trips in opposite direction during morning and afternoon.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route71/",
    "route_color": "B67F72",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8270,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 72,
    "route_long_name": "",
    "route_service_name": "MIDDLTON:CAP SQR",
    "route_desc": "Serves Middleton to/from Capitol Square. Operates regularly in Capitol Square direction from about 6 AM to 9 AM and in Middleton direction from about 3 PM to 6 PM on weekday service days only; limited trips in opposite direction during morning and afternoon.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route72/",
    "route_color": "841D1D",
    "route_text_color": "FFFFFF",
    "bikes_allowed": 1
  },
  {
    "route_id": 8271,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 73,
    "route_long_name": "",
    "route_service_name": "MIDDLTON:WEST TP",
    "route_desc": "Serves West Transfer Point to/from Middleton. Operates regularly in both directions during entire day on weekday service days only.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route73/",
    "route_color": "DFB93E",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8272,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 75,
    "route_long_name": "",
    "route_service_name": "VERONA:CAP SQR",
    "route_desc": "Serves Capitol Square to/from Verona-Epic Campus. Operates limited trips in both directions in the morning and afternoon on weekday and modified service days only.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route75/",
    "route_color": "E0993A",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8273,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 78,
    "route_long_name": "",
    "route_service_name": "MIDDLTON:WEST TP",
    "route_desc": "Serves West Transfer Point to/from Middleton. Operates regularly during entire day on Saturday and modified service days only.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route78/",
    "route_color": "365AA6",
    "route_text_color": "FFFFFF",
    "bikes_allowed": 1
  },
  {
    "route_id": 8274,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 80,
    "route_long_name": "",
    "route_service_name": "EAGLE HT:UW UNION",
    "route_desc": "Serves Memorial Union to/from UW Hospital-Eagle Heights. Operates regularly in both directions during weekday and weekend UW standard and recess service days only; see UW service calendar printed in Metro Ride Guide or on Metro website.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route80/",
    "route_color": "B33927",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8275,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 81,
    "route_long_name": "",
    "route_service_name": "OBSRVTRY/JOHNSON:UNION",
    "route_desc": "Serves Memorial Union to/from Observatory-Johnson. Operates regularly on every service day from about 6 PM to 3 AM during UW standard service days only; see UW service calendar printed in Metro Ride Guide or on Metro website.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route81/",
    "route_color": "DD9139",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8276,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 82,
    "route_long_name": "",
    "route_service_name": "BREESE/W WASH:UNION",
    "route_desc": "Serves Memorial Union to/from Breese-W Washington. Operates regularly on every service day from about 6 PM to 3 AM during UW standard service days only; see UW service calendar printed in Metro Ride Guide or on Metro website.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route82/",
    "route_color": "3F6AB2",
    "route_text_color": "000000",
    "bikes_allowed": 1
  },
  {
    "route_id": 8277,
    "service_id": 84,
    "agency_id": "MMT",
    "route_short_name": 84,
    "route_long_name": "",
    "route_service_name": "EAGLE HT:U CAMPUS",
    "route_desc": "Serves UW Campus to Eagle Heights. Operates regularly from about 4 PM to 6 PM during weekday UW standard and recess service days only; see UW service calendar printed in Metro Ride Guide or on Metro website.",
    "route_type": 3,
    "route_url": "http://www.cityofmadison.com/Metro/schedules/Route84/",
    "route_color": "60348E",
    "route_text_color": "000000",
    "bikes_allowed": 1
  }
]