name: Deploy to production
on:
  push:
    branches:
    - 'github-actions'

jobs:
  update-dynamo-tables:
    runs-on: ubuntu-latest
    if: git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -q "gtfs/"; then
      echo "The file or directory was modified."
    #if: ${{ contains(github.event.head_commit.modified, 'gtfs/') }}
    steps:
        - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
        - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
        - name: Check out repo
          uses: actions/checkout@v3

        - name: Setup Node environment
          uses: actions/setup-node@v3
          with:
            node-version: '18'

        - name: npm install
          run: npm install
          
        - name: set AWS creds
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

        - name: import new TRIP data
          run: npm run trip-import
          
        - name: import new STOPS data
          run: npm run stop-import

  deploy-lambda:
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        
      - name: Setup Node environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: npm install
        run: npm install    

      - name: Build a zip file
        run: zip -r function.zip .

      - name: set AWS creds
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy to Lambda
        run: aws lambda update-function-code --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} --zip-file fileb://function.zip

